In [ ]:
# We have something called SONAR used in submarines,
# where the data from that SONAR is used to tell if the object detected by the SONAR is a rock or a mine
# kinda military use case.... 
# work flow : The Sonar data from lab is collected -> Then the data is undergone some preprocessing
# -> now we will split our data to train data and test data -> this data is feed into a model(for this case we will use Logistic Regression model)
# -> then we will take this trained model and take some real world or new data that the model is not trained with and we check how accurate it is...

In [22]:
# since everything is in numaric value, no need to do vectorization
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [23]:
# Now we work with the data
datadf = pd.read_csv("Copy of sonar data.csv", header=None)
# our dataset has no headers, so have to let the pandas know that there are no headers,
# if we dont the first row(in our case which is actually data not header of table), pandas will take that as header
# now since we told panda that we don't have any header it will put indexes

In [24]:
datadf.head()
# the indexes start from 0 to n-1

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [25]:
# now the number of rows and columns are
print(datadf.shape)
# we have 208 rows and 60 features + 1 target(result/label)

(208, 61)

In [26]:
# now lets see how man rock and how many mines we have in our data set
datadf[60].value_counts()
# output:
# M    111
# R     97
# Name: count, dtype: int64
# the number of M and R are almost equal so, its fine.....
# the data is less but for a small model, its alright
# but if we get more data, more accurate our model will be

60
M    111
R     97
Name: count, dtype: int64

In [27]:
# Now we can check the mean value of the values that are mine or rock
# we can use groupby() to group these M and R and then mean() to get the mean
datadf.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [28]:
# Now we are gonna separate data and label
X= datadf.drop(columns=60, axis=1) # 0-59 columns
Y=datadf[60] # 60th column

In [29]:
# Now we will split the data based on train and test
X_train,X_test,Y_train, Y_test = train_test_split(X,Y, test_size=0.15, stratify=Y, random_state=4)

In [30]:
model = LogisticRegression()
# the model: LogisticRegression

In [31]:
model.fit(X_train, Y_train)
# train the model with training data

LogisticRegression()

In [32]:
# Now we can check the accuracy how well the model is trained
# ofc since the data is less, the accuracy will be low
# now we will trian to test with the test data, that model have never seen
X_test_prediction = model.predict(X_test)
# now the model predicts the data of Y_test using the X_test
# now that we will compare with the Y_test
acc_score = accuracy_score(X_test_prediction, Y_test)
print(acc_score)
#ouptut: 0.75
# that means out of 100 values 75 will be right, might look bad but the accuracy it has got just from such small data is awsome
# we only had like 200 data sets, in real we get 100000+++, it will be way more accurate than this

0.75